---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: capacitor

components:
  - ../../components/config-common

resources:
  - namespace.yaml
  - helm.yaml
  - network-policy.yaml
  - route.yaml
