services:
  traefik:
    image: traefik:v3
    command:
      - --api=true
      - --accesslog=true
      - --providers.docker
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.${DOMAIN}`)
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      # Uncomment for HTTPS
      # - --entrypoints.web.http.redirections.entrypoint.to=websecure
      # - --entryPoints.web.http.redirections.entrypoint.scheme=https
      # - --entrypoints.websecure.address=:443
      # - --entrypoints.websecure.asDefault=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.service=api@internal

  coredns:
    image: coredns/coredns:1.12.1
    ports:
      - 53:53/tcp
      - 53:53/udp
    configs:
      - source: coredns_config
        target: /Corefile
        mode: 444
    command: -conf /Corefile
    env_file:
      - .env

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true

  portainer:
    image: ngxson/portainer-ce-without-annoying:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true

      # Frontend
      - traefik.http.routers.frontend.rule=Host(`portainer.${DOMAIN}`)
      - traefik.http.routers.frontend.service=frontend
      - traefik.http.services.frontend.loadbalancer.server.port=9000

      # Edge
      - traefik.http.routers.edge.rule=Host(`edge.${DOMAIN}`)
      - traefik.http.routers.edge.service=edge
      - traefik.http.services.edge.loadbalancer.server.port=8000

configs:
  coredns_config:
    file: ./Corefile

volumes:
  portainer_data:
