---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: postgres
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: postgres
spec:
  interval: 24h
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  install:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values-postgres.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster
  namespace: postgres
spec:
  interval: 24h
  dependsOn:
    - name: operator
  chart:
    spec:
      chart: cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  install:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values-cluster.yaml
