---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
namespace: postgres

components:
  - ../../components/config-common

resources:
  - namespace.yaml
  - helm.yaml

configMapGenerator:
  - name: helm-values
    files:
      - values-postgres.yaml
      - values-cluster.yaml
