---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: load-balancer
namespace: load-balancer

components:
  - ../../components/config-common

resources:
  - namespace.yaml
  - helm.yaml
  - address-pool.yaml

configMapGenerator:
  - name: helm-values
    files:
      - values-metallb.yaml
