controller:
  repository: quay.io/metallb/controller
  tag: v0.14.9
  pullPolicy: IfNotPresent
speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.15.0@sha256:f033befd5aa69ce2449b437cdf0b3d756d55d4f333c1b16e836399f03f3b2767
    pullPolicy: IfNotPresent
  frr:
    enabled: false

prometheus:
  serviceAccount: prometheus-kube-prometheus-prometheus
  namespace: metrics
  serviceMonitor:
    enabled: true
