---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: traefik
spec:
  interval: 24h
  chart:
    spec:
      chart: traefik-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    crds: CreateReplace
  values:
    traefik: false
    gatewayAPI: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  dependsOn:
    - name: traefik-crds
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    crds: Skip
  values:
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesCRD:
        enabled: false
      kubernetesGateway:
        enabled: true
        statusAddress:
          service:
            enabled: true

    gateway:
      listeners:
        web:
          namespacePolicy: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
  hostnames:
    - traefik.localhost
  rules:
    - backendRefs:
        - kind: TraefikService
          name: api@internal
