---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: gateway
spec:
  interval: 1m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: gateway
spec:
  interval: 24h
  chart:
    spec:
      chart: traefik-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values-traefik-crds.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: gateway
spec:
  interval: 24h
  dependsOn:
    - name: traefik-crds
    - name: prometheus
      namespace: metrics
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    crds: Skip
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values-traefik.yaml
