---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gateway
namespace: gateway

components:
  - ../../components/config-common

resources:
  - namespace.yml
  - helm.yml
  - route.yml

configMapGenerator:
  - name: helm-values
    files:
      - values-traefik.yml
      - values-traefik-crds.yml
