providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    enabled: false
  kubernetesGateway:
    enabled: true
    statusAddress:
      service:
        enabled: true

service:
  annotations:
    metallb.io/loadBalancerIPs: 10.42.42.1

gateway:
  listeners:
    web:
      namespacePolicy: All
