---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: metrics
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-crds
  namespace: metrics
spec:
  interval: 24h
  chart:
    spec:
      chart: prometheus-operator-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
  install:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: metrics
spec:
  interval: 24h
  dependsOn:
    - name: prometheus-crds
    - name: traefik-crds
      namespace: gateway
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
  install:
    crds: Skip
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values-prometheus.yaml
