---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metrics
namespace: metrics

components:
  - ../../components/config-common

resources:
  - namespace.yml
  - helm.yml

configMapGenerator:
  - name: helm-values
    files:
      - values-prometheus.yml
