crds:
  enabled: false
prometheus:
  prometheusSpec:
    maximumStartupDurationSeconds: null

    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
  route:
    main:
      enabled: true
      hostnames:
        - prometheus.localhost
      parentRefs:
        - kind: Gateway
          name: traefik-gateway
          namespace: gateway
grafana:
  route:
    main:
      enabled: true
      hostnames:
        - grafana.localhost
      parentRefs:
        - kind: Gateway
          name: traefik-gateway
          namespace: gateway
