---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coredns
  namespace: dns
  labels:
    app.kubernetes.io/component: coredns
spec:
  interval: 1m0s
  url: https://coredns.github.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: dns
  labels:
    app.kubernetes.io/component: coredns
spec:
  interval: 24h
  chart:
    spec:
      chart: coredns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coredns
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values-coredns.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: ClusterRole
              name: coredns
            patch: |
              - op: replace
                path: /rules
                value:
                  - apiGroups:
                      - apiextensions.k8s.io
                    resources:
                      - customresourcedefinitions
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - discovery.k8s.io
                    resources:
                      - endpointslices
                    verbs:
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - services
                      - namespaces
                    verbs:
                      - list
                      - watch
                  - apiGroups:
                      - extensions
                      - networking.k8s.io
                    resources:
                      - ingresses
                    verbs:
                      - list
                      - watch
                  - apiGroups: ["gateway.networking.k8s.io"]
                    resources: ["*"]
                    verbs: ["watch", "list"]
                  - apiGroups: ["k8s.nginx.org"]
                    resources: ["*"]
                    verbs: ["watch", "list"]
