isClusterService: false
image:
  repository: ghcr.io/k8s-gateway/k8s_gateway
  tag: 1.2.1@sha256:7830e736192ec17039a0c6f5302d025e93cc323b15b8e74c69fcdeb895062a5b
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
serviceType: LoadBalancer
service:
  loadBalancerIP: 10.42.42.0
servers:
  - zones:
      - zone: .
        scheme: dns://
        use_tcp: true
    port: 53
    plugins:
      - name: any
      - name: debug
      - name: errors
      - name: health
      - name: ready
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: loadbalance

      - name: k8s_gateway
        parameters: localhost
        configBlock: |-
          resources HTTPRoute
      - name: cache
        parameters: 30 localhost

      - name: forward
        parameters: ballard.coldencullen.com 10.0.1.1
      - name: forward
        parameters: mission.coldencullen.com 10.1.1.1

      - name: forward
        parameters: . tls://1.1.1.1 tls://1.0.0.1
        configBlock: |-
          tls
          tls_servername one.one.one.one
