isClusterService: false
image:
  repository: ghcr.io/k8s-gateway/k8s_gateway
  tag: 1.2.0@sha256:41bce7edf43b0d9a3f2ddcc4c64bbc5af2d7aaf8cd19a472e34a3981c20f059b
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
serviceType: LoadBalancer
service:
  loadBalancerIP: 10.42.42.0
servers:
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: debug
      - name: errors
      - name: health
      - name: ready
      - name: k8s_gateway
        parameters: localhost
        configBlock: |-
          resources HTTPRoute
          fallthrough
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: cache
        parameters: 30
      - name: loadbalance
