name: On Commit CI
on:
  - push

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  kubectl-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint yamls
        uses: stackrox/kube-linter-action@v1
        with:
          directory: stacks

  tilt-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Latest Homebrew
        id: brew-version
        run: echo version=$(gh api repos/Homebrew/brew/releases -q '.[0].tag_name') >> "$GITHUB_OUTPUT"

      - name: Cache Homebrew
        uses: actions/cache@v4
        id: cache-brew
        with:
          path: /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-${{ steps.brew-version.outputs.version }}

      - name: Install Homebrew
        if: steps.cache-brew.outputs.cache-hit != 'true'
        run: bash -c "CI=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Setup Homebrew (pt 1)
        run: /home/linuxbrew/.linuxbrew/bin/brew shellenv --shell=bash | grep HOMEBREW_ | cut -d' ' -f2- | cut -d';' -f1 >> "$GITHUB_ENV"

      - name: Setup Homebrew (pt 2)
        run: echo ${{ env.HOMEBREW_PREFIX }}/bin:${{ env.HOMEBREW_PREFIX }}/sbin >> "$GITHUB_PATH"

      - name: Cache Homebew Bundle
        uses: actions/cache@v4
        id: cache-bundle
        with:
          path: |
            ${{ env.HOMEBREW_CELLAR }}
            ${{ env.HOMEBREW_PREFIX }}/bin
            ${{ env.HOMEBREW_PREFIX }}/sbin
          key: ${{ runner.os }}-${{ steps.brew-version.outputs.version }}-${{ hashFiles('Brewfile') }}

      - name: Install Homebrew Bundle
        if: steps.cache-bundle.outputs.cache-hit != 'true'
        run: brew bundle install

      - name: Setup Cluster
        run: ctlptl apply -f cluster-kind.yml

      - name: Run Tilt CI
        run: tilt ci
