name: On Commit CI
on:
  - push

jobs:
  pre-commit:
    name: Pre-Commit Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      - uses: ./.github/actions/setup-homebrew
        with:
          github-token: ${{ github.token }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: no-commit-to-branch

  tilt-ci:
    name: Tilt CI - ${{ matrix.runtime.name }} - ${{ matrix.mode.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - name: Kind
            create: ctlptl apply -f cluster-kind.yaml
        mode:
          - name: Tilt Mode
            args: ""
          - name: Flux Mode
            args: --flux-mode
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ./.github/actions/setup-homebrew
        with:
          github-token: ${{ github.token }}

      - name: Setup Cluster
        run: ${{ matrix.runtime.create }}

      - name: Run Tilt CI (${{ matrix.mode.name }})
        run: tilt ci -- ${{ matrix.mode.args }}
